steps:
  # Build da imagem Docker com cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mindfuljung-api'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/mindfuljung-api'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: '900s'

  # Push para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mindfuljung-api']
    timeout: '600s'

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mindfuljung-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mindfuljung-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8000'
      - '--timeout'
      - '3600'
      - '--execution-environment'
      - 'gen2'
      - '--cpu-boost'
      - '--set-secrets'
      - 'OPENAI_API_KEY=mindfuljung-openai-key:latest,PINECONE_API_KEY=mindfuljung-pinecone-key:latest,PINECONE_INDEX_HOST=mindfuljung-pinecone-host:latest'
      - '--env-vars-file'
      - 'env.yaml'
    timeout: '600s'

# Configurações globais
timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - 'gcr.io/$PROJECT_ID/mindfuljung-api' 